[package]
name = "shiftbbs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.0"
encoding_rs = "0.8.31"
serde = { version = "1.0.138", features = ["derive"] }
toml = "0.5.9"
